const MAX_RATING = 9;
const AMOUNT_CARDS = 17;
const EXTRA_AMOUNT_CARDS = 2;
const AMOUNT_COMMENTS = 10;
const SHOWING_CARDS_AMOUNT_ON_START = 5;
const SHOWING_CARDS_AMOUNT_BY_BUTTON = 5;
const VALUES_FOR_USER_RANK = [1, 10, 11, 20];

export {
  MAX_RATING, AMOUNT_CARDS, EXTRA_AMOUNT_CARDS, AMOUNT_COMMENTS, SHOWING_CARDS_AMOUNT_ON_START,
  SHOWING_CARDS_AMOUNT_BY_BUTTON, VALUES_FOR_USER_RANK
};
